/**
 * Template marketplace data - production-grade
 */

import type { Template } from "./template-schema";

export const TEMPLATES: Template[] = [
  {
    id: "wedding-invitation-gold",
    name: "Elegant Wedding Invitation",
    slug: "elegant-wedding-invitation",
    nicheId: "wedding",
    category: "Invitation",
    description: "Cinematic wedding invitation video with golden accents and romantic visuals.",
    useCases: ["Wedding invites", "Save the date", "Anniversary"],
    thumbnail: "/templates/wedding-invite.jpg",
    duration: 10,
    style: "cinematic",
    languages: ["English", "Tamil", "Hindi", "Telugu"],
    creditsCost: 10,
    isTrending: true,
    inputFields: [
      { id: "f1", key: "name", label: "Couple Names", type: "text", placeholder: "John & Jane", required: true, promptVariable: "name" },
      { id: "f2", key: "date", label: "Wedding Date", type: "date", required: true, promptVariable: "date" },
      { id: "f3", key: "location", label: "Venue", type: "text", placeholder: "Grand Palace, Chennai", promptVariable: "location" },
      { id: "f4", key: "message", label: "Personal Message", type: "textarea", placeholder: "We invite you to celebrate...", promptVariable: "message" },
    ],
    promptTemplate: "Elegant cinematic wedding invitation video. Couple names: {{name}}. Wedding date: {{date}}. Venue: {{location}}. Message: {{message}}. Golden accents, romantic lighting, soft music.",
  },
  {
    id: "business-product-launch",
    name: "Product Launch Promo",
    slug: "product-launch-promo",
    nicheId: "business",
    category: "Promo",
    description: "Professional product launch video with dynamic transitions.",
    useCases: ["Product launch", "App release", "Service intro"],
    thumbnail: "/templates/business-promo.jpg",
    duration: 15,
    style: "cinematic",
    languages: ["English", "Hindi"],
    creditsCost: 15,
    isRecommended: true,
    inputFields: [
      { id: "f1", key: "businessName", label: "Business Name", type: "text", required: true, promptVariable: "businessName" },
      { id: "f2", key: "productName", label: "Product/Service", type: "text", required: true, promptVariable: "productName" },
      { id: "f3", key: "offerText", label: "Offer / CTA", type: "text", placeholder: "Launch offer 20% off", promptVariable: "offerText" },
    ],
    promptTemplate: "Professional cinematic product launch video. Business: {{businessName}}. Product: {{productName}}. Offer: {{offerText}}. Dynamic transitions, premium feel.",
  },
  {
    id: "temple-greeting",
    name: "Temple Blessing Video",
    slug: "temple-blessing-video",
    nicheId: "temple",
    category: "Greeting",
    description: "Sacred temple visuals with devotional aesthetics.",
    useCases: ["Temple events", "Religious greetings", "Festival wishes"],
    thumbnail: "/templates/temple.jpg",
    duration: 10,
    style: "cinematic",
    languages: ["Tamil", "Hindi", "Telugu", "English"],
    creditsCost: 10,
    inputFields: [
      { id: "f1", key: "name", label: "Name", type: "text", required: true, promptVariable: "name" },
      { id: "f2", key: "message", label: "Blessing Message", type: "textarea", promptVariable: "message" },
    ],
    promptTemplate: "Sacred cinematic temple video. Name: {{name}}. Message: {{message}}. Devotional aesthetics, golden temple visuals, peaceful atmosphere.",
  },
  {
    id: "diwali-greeting",
    name: "Diwali Festival Greeting",
    slug: "diwali-festival-greeting",
    nicheId: "festival",
    category: "Festival",
    description: "Vibrant Diwali lights and celebration visuals.",
    useCases: ["Diwali", "Festival wishes", "New Year"],
    thumbnail: "/templates/diwali.jpg",
    duration: 10,
    style: "cinematic",
    languages: ["Hindi", "English", "Tamil"],
    creditsCost: 10,
    isTrending: true,
    inputFields: [
      { id: "f1", key: "name", label: "Your Name", type: "text", required: true, promptVariable: "name" },
      { id: "f2", key: "message", label: "Greeting Message", type: "textarea", placeholder: "Wishing you a prosperous Diwali", promptVariable: "message" },
    ],
    promptTemplate: "Vibrant Diwali festival greeting video. From: {{name}}. Message: {{message}}. Diya lights, fireworks, festive colors, celebration atmosphere.",
  },
  {
    id: "horoscope-daily",
    name: "Daily Horoscope Video",
    slug: "daily-horoscope-video",
    nicheId: "astrology",
    category: "Horoscope",
    description: "Cosmic visuals with zodiac-themed aesthetics.",
    useCases: ["Daily horoscope", "Zodiac content", "Astrology channel"],
    thumbnail: "/templates/horoscope.jpg",
    duration: 10,
    style: "fantasy",
    languages: ["English", "Tamil", "Hindi"],
    creditsCost: 10,
    inputFields: [
      { id: "f1", key: "zodiacSign", label: "Zodiac Sign", type: "text", placeholder: "Aries, Taurus...", required: true, promptVariable: "zodiacSign" },
      { id: "f2", key: "message", label: "Prediction Text", type: "textarea", required: true, promptVariable: "message" },
    ],
    promptTemplate: "Cosmic cinematic horoscope video. Zodiac: {{zodiacSign}}. Prediction: {{message}}. Stars, galaxies, mystical atmosphere.",
  },
  {
    id: "political-rally",
    name: "Political Rally Promo",
    slug: "political-rally-promo",
    nicheId: "political",
    category: "Campaign",
    description: "Powerful campaign video with rally energy.",
    useCases: ["Election campaign", "Rally promo", "Party intro"],
    thumbnail: "/templates/political.jpg",
    duration: 15,
    style: "cinematic",
    languages: ["Hindi", "Tamil", "Telugu", "English"],
    creditsCost: 15,
    inputFields: [
      { id: "f1", key: "name", label: "Candidate/Party Name", type: "text", required: true, promptVariable: "name" },
      { id: "f2", key: "slogan", label: "Slogan", type: "text", promptVariable: "slogan" },
      { id: "f3", key: "message", label: "Key Message", type: "textarea", promptVariable: "message" },
    ],
    promptTemplate: "Powerful political rally cinematic video. Candidate: {{name}}. Slogan: {{slogan}}. Message: {{message}}. Crowd, flags, energetic atmosphere.",
  },
  {
    id: "travel-montage",
    name: "Travel Cinematic Montage",
    slug: "travel-cinematic-montage",
    nicheId: "travel",
    category: "Travel",
    description: "Stunning travel destination montage.",
    useCases: ["Travel vlog", "Destination promo", "Vacation recap"],
    thumbnail: "/templates/travel.jpg",
    duration: 15,
    style: "cinematic",
    languages: ["English"],
    creditsCost: 15,
    isRecommended: true,
    inputFields: [
      { id: "f1", key: "destination", label: "Destination", type: "text", placeholder: "Goa, Kerala, Paris", required: true, promptVariable: "destination" },
      { id: "f2", key: "message", label: "Caption / Story", type: "textarea", promptVariable: "message" },
    ],
    promptTemplate: "Stunning cinematic travel montage. Destination: {{destination}}. Story: {{message}}. Drone shots, golden hour, wanderlust feel.",
  },
  {
    id: "reels-trending",
    name: "Trending Reels Template",
    slug: "trending-reels-template",
    nicheId: "social",
    category: "Reels",
    description: "Viral-style vertical video for Instagram/TikTok.",
    useCases: ["Instagram Reels", "TikTok", "YouTube Shorts"],
    thumbnail: "/templates/reels.jpg",
    duration: 5,
    style: "cinematic",
    languages: ["English", "Hindi", "Tamil"],
    creditsCost: 8,
    isTrending: true,
    inputFields: [
      { id: "f1", key: "message", label: "Hook / Caption", type: "text", required: true, promptVariable: "message" },
    ],
    promptTemplate: "Trending vertical cinematic reel. Hook: {{message}}. Fast cuts, viral style, 9:16 aspect ratio.",
  },
  {
    id: "birthday-celebration",
    name: "Birthday Celebration Video",
    slug: "birthday-celebration-video",
    nicheId: "wedding",
    category: "Birthday",
    description: "Joyful birthday celebration with party vibes.",
    useCases: ["Birthday wishes", "Party invite", "Milestone"],
    thumbnail: "/templates/birthday.jpg",
    duration: 10,
    style: "cinematic",
    languages: ["English", "Tamil", "Hindi"],
    creditsCost: 10,
    inputFields: [
      { id: "f1", key: "name", label: "Name", type: "text", required: true, promptVariable: "name" },
      { id: "f2", key: "age", label: "Age (optional)", type: "number", promptVariable: "age" },
      { id: "f3", key: "message", label: "Wish Message", type: "textarea", promptVariable: "message" },
    ],
    promptTemplate: "Joyful birthday celebration video. Name: {{name}}. Age: {{age}}. Message: {{message}}. Balloons, cake, party atmosphere.",
  },
];

export const getTemplatesByNiche = (nicheId: string) =>
  TEMPLATES.filter((t) => t.nicheId === nicheId);

export const getTemplateById = (id: string) => TEMPLATES.find((t) => t.id === id);

export const getTrendingTemplates = () => TEMPLATES.filter((t) => t.isTrending);

export const getRecommendedTemplates = () => TEMPLATES.filter((t) => t.isRecommended);
